# site settings
title: Bloei en Leef
email: info@bloeienleef.nl
description: Bloei en Leef staat voor een gezonde en eerlijke levensstijl.
baseurl: ""
url: "http://localhost:"
permalink: pretty

# collections
collections:
  recepten:
    output: true

  weetjes:
    output: true

  blogs:
    output: true

tipue_search:
  include:
    pages: true
    collections: [recepten, weetjes, blogs]
